# tasks file for ufw
---
- name: fix dropped ssh sessions | configure kernel
  sysctl:
    name: net.netfilter.nf_conntrack_tcp_be_liberal
    value: 1
    state: present
    sysctl_set: true
    reload: true
  tags:
    - ufw-fix-dropped-ssh-sessions-configure-kernel
