---
- name: Converge
  hosts: all
  become: true
  pre_tasks:
    - name: Include test variables
      ansible.builtin.include_vars: "{{ playbook_dir }}/../../tests/vars/main.yml"
  roles:
    - ../../../
